version: '2'
services:
  pessoa-postgresql:
    image: postgres:11.3
    # volumes:
    #     - ~/volumes/pessoa/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=pessoa
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
